#version 440 core

layout(local_size_x=WORKGROUP_SIZE)in;

layout(binding=0,std430)buffer HDB{vec2 HDBBuffer[];};
layout(rg32f,binding=0)writeonly uniform image2D HDBImage;

uniform uint HDBSize=0;

void main(){
  if(gl_GlobalInvocationID.x>=HDBSize)return;
  imageStore(
    HDBImage,
    ivec2(gl_GlobalInvocationID.x%TESTSIZE,gl_GlobalInvocationID.x/TESTSIZE),
    vec4(HDBBuffer[gl_GlobalInvocationID.x],0,0));
}
